apiVersion: v2
name: soltech-idp
description: SOLTECH configured Keycloak
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: keycloak
    version: 12.3.0
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql
    condition: database.provider.postgresql
    version: 11.9.13
    repository: https://charts.bitnami.com/bitnami
  - name: mariadb
    condition: database.provider.mariadb
    version: 11.4.2
    repository: https://charts.bitnami.com/bitnami
