hooks:
  postgresql:
    image:
      repository: docker.io/bitnami
      name: postgresql
      tag: 14.5.0-debian-11-r35
      pullPolicy: IfNotPresent
  mariadb:
    image:
      repository: docker.io/bitnami
      name: mariadb
      tag: 10.6.11-debian-11-r12
      pullPolicy: IfNotPresent
  alpine:
    image:
      repository: docker.io
      name: alpine
      tag: 3.16.3
      pullPolicy: IfNotPresent

keycloak:
  service:
    type: ClusterIP
    ports: 
      http: 443

  httpRelativePath: "/auth/"

  auth:
    adminUser: keycloak
    existingSecret: idp-keycloak

  externalDatabase:
    existingSecret: idp-keycloak
    user: keycloak
    database: keycloak

  ingress:
    enabled: true
    path: "/auth"
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"

  postgresql:
    enabled: false

database:
  provider:
    postgresql: false
    mariadb: false
  initialize: false
  install: false

secrets:
  database:
    user: postgres
    password: test123

  keycloak:
    database:
      user: keycloak
      password: test123
