database:
  provider:
    postgresql: true
  environment: local

postgresql:
  global:
    postgresql:
      auth:
        existingSecret: idp-database

  primary:
    service:
      type: NodePort
      nodePorts:
        postgresql: "30432"

keycloak:
  externalDatabase:
    host: idp-postgresql
    port: 5432

  initContainers:
    - name: service-check
      image: "docker.io/alpine:3.15.4"
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c"]
      args:
        - /nc-hooks/nc-services.sh
      env:
        - name: DATABASE_HOST
          value: idp-postgresql
        - name: DATABASE_PORT
          value: "5432"
      volumeMounts:
        - name: nc-services
          mountPath: /nc-hooks
      resources:
        limits:
          cpu: "250m"
          memory: "256Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"

  extraVolumes:
    - name: nc-services
      configMap:
        name: "idp-nc-services"
        defaultMode: 0755

