{{- if or .Values.database.install .Values.database.initialize }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database
  labels:
  {{- include "soltech-idp.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "1"
    "helm.sh/hook": pre-install
type: Opaque
data:
  {{ if .Values.secrets.postgresql.master }}
  PGPASSWORD: {{ .Values.secrets.postgresql.master | b64enc }}
  postgres-password: {{ .Values.secrets.postgresql.master | b64enc }}
  {{- else }}
  {{- $postgresqlSecret := randAlphaNum 32 }}
  PGPASSWORD: {{ $postgresqlSecret | b64enc }}
  postgres-password: {{ $postgresqlSecret | b64enc }}
  {{- end }}
  {{ if .Values.secrets.mariadb.root }}
  MARIADB_ROOT_PASSWORD: {{ .Values.secrets.mariadb.root | b64enc }}
  mariadb-root-password: {{ .Values.secrets.mariadb.root | b64enc }}
  {{- else }}
  {{- $mariadbSecret := randAlphaNum 32 }}
  MARIADB_ROOT_PASSWORD: {{ $mariadbSecret | b64enc }}
  mariadb-root-password: {{ $mariadbSecret | b64enc }}
  {{- end }}
{{- end }}