apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keycloak
  labels:
  {{- include "soltech-idp.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "1"
    "helm.sh/hook": pre-install
type: Opaque
data:
  admin-password: {{ randAlphaNum 32 | b64enc }}
  db-password: {{ .Values.secrets.keycloak.database.password | b64enc }}
  KEYCLOAK_DATABASE_PASSWORD: {{ .Values.secrets.keycloak.database.password | b64enc }}
